// src/components/config/ConfigFileGrid.tsx
import { Text } from "@fluentui/react-components";
import { DocumentCopyRegular } from "@fluentui/react-icons";
import { useAppStore } from "../../stores/appStore";
import ConfigFileCard from "./ConfigFileCard";

export default function ConfigFileGrid() {
  const configFiles = useAppStore((state) => state.configFiles);
  const selectedConfigPath = useAppStore((state) => state.appSettings.app.selected_config_path);
  const subscriptions = useAppStore((state) => state.subscriptions);
  const pendingOperations = useAppStore((state) => state.pendingOperations);
  
  const hasConfigFiles = configFiles.length > 0;
  const isLoading = pendingOperations > 0;

  if (!hasConfigFiles) {
    return (
      <div className="flex flex-col items-center justify-center py-16 text-center text-neutral-500">
        <DocumentCopyRegular className="text-6xl opacity-30 mb-4" />
        <Text size={500} weight="semibold" className="mb-2 text-neutral-300">
          No Configuration Files
        </Text>
        <Text className="max-w-md">
          Add a configuration file by subscribing to a URL or selecting a local file
        </Text>
      </div>
    );
  }

  return (
    <div className="grid w-full gap-4 mt-4" style={{ gridTemplateColumns: "repeat(auto-fit, minmax(320px, 1fr))" }}>
      {configFiles.map((config) => (
        <ConfigFileCard
          key={config.path}
          config={config}
          isSelected={config.path === selectedConfigPath}
          subscription={subscriptions[config.displayName]}
          isLoading={isLoading}
        />
      ))}
    </div>
  );
}

// src/components/config/ConfigFileGrid.vue
<script setup lang="ts">
import { computed } from "vue";
import ConfigFileCard from "./ConfigFileCard.vue";
import { useAppStore } from "../../stores/appStore";

const appStore = useAppStore();
const hasConfigFiles = computed(() => appStore.configFiles.value.length > 0);
</script>

<template>
  <div class="mt-6 min-h-0 grow overflow-y-auto">
    <div
      v-if="!hasConfigFiles"
      class="flex flex-col items-center justify-center py-16 text-center"
    >
      <div class="mb-4 text-6xl opacity-50">📄</div>
      <h3 class="mb-2 text-xl font-semibold text-gray-700">
        No Configuration Files
      </h3>
      <p class="max-w-md text-gray-500">
        Add a configuration file by subscribing to a URL or selecting a local
        file
      </p>
    </div>

    <div
      v-else
      class="grid gap-4"
      style="grid-template-columns: repeat(auto-fill, minmax(320px, 1fr))"
    >
      <ConfigFileCard
        v-for="config in appStore.configFiles.value"
        :key="config.path"
        :config="config"
        :is-selected="config.path === appStore.selectedConfigPath.value"
        :subscription="appStore.subscriptions.value[config.displayName]"
        :is-loading="appStore.isLoading.value"
      />
    </div>
  </div>
</template>
