// src/components/config/SubscriptionList.tsx
import { useState, useMemo } from "react";
import { Input, Button, Spinner } from "@fluentui/react-components";
import { ArrowDownloadRegular, FolderOpenRegular } from "@fluentui/react-icons";
import { useAppStore } from "../../stores/appStore";
import { useConfigs } from "../../hooks/useConfigs";

export default function SubscriptionList() {
  const [subscriptionUrl, setSubscriptionUrl] = useState("");
  const pendingOperations = useAppStore((state) => state.pendingOperations);
  const configs = useConfigs();

  const isLoading = pendingOperations > 0;
  const canAddSubscription = useMemo(
    () => !!subscriptionUrl.trim() && !isLoading,
    [subscriptionUrl, isLoading]
  );

  const submitSubscription = () => {
    if (!canAddSubscription) return;
    void configs.addSubscription(subscriptionUrl.trim());
    setSubscriptionUrl("");
  };

  return (
    <div className="flex flex-col gap-3 w-full">
      <div className="flex flex-col md:flex-row gap-3">
        <Input
          value={subscriptionUrl}
          onChange={(_, data) => setSubscriptionUrl(data.value)}
          disabled={isLoading}
          placeholder="Enter subscription URL"
          className="flex-1"
          onKeyDown={(e) => {
            if (e.key === "Enter") submitSubscription();
          }}
        />
        <Button
          appearance="primary"
          icon={isLoading ? <Spinner size="extra-tiny" /> : <ArrowDownloadRegular />}
          disabled={!canAddSubscription}
          onClick={submitSubscription}
        >
          {isLoading ? "Subscribing..." : "Subscribe"}
        </Button>
      </div>
      <div className="flex w-full">
        <Button
          appearance="secondary"
          icon={<FolderOpenRegular />}
          disabled={isLoading}
          onClick={() => void configs.selectConfigFile()}
          className="w-full"
        >
          Add Config
        </Button>
      </div>
    </div>
  );
}

// src/components/config/SubscriptionList.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import { useAppStore } from "../../stores/appStore";
import { useConfigs } from "../../composables/useConfigs";

const appStore = useAppStore();
const configs = useConfigs();
const subscriptionUrl = ref("");

const canAddSubscription = computed(
  () => !!subscriptionUrl.value.trim() && !appStore.isLoading.value,
);

function submitSubscription() {
  if (!canAddSubscription.value) {
    return;
  }

  void configs.addSubscription(subscriptionUrl.value.trim());
  subscriptionUrl.value = "";
}
</script>

<template>
  <div class="flex w-full flex-col gap-3">
    <div class="flex flex-col gap-3 md:flex-row">
      <input
        v-model="subscriptionUrl"
        type="text"
        class="flex-1 rounded-lg border border-gray-300 px-4 py-2.5 text-sm outline-none transition-all duration-200 focus:border-blue-500 focus:ring-2 focus:ring-blue-200"
        placeholder="Enter subscription URL"
        :disabled="appStore.isLoading.value"
        @keyup.enter="submitSubscription"
      />
      <button
        class="control-button subscribe-button"
        :disabled="!canAddSubscription"
        :class="{ disabled: !canAddSubscription }"
        @click="submitSubscription"
      >
        <span class="mr-3 text-lg">📥</span>
        {{ appStore.isLoading.value ? "Subscribing..." : "Subscribe" }}
      </button>
    </div>
    <div class="flex w-full">
      <button
        class="control-button select-button w-full justify-center"
        :disabled="appStore.isLoading.value"
        :class="{ disabled: appStore.isLoading.value }"
        @click="configs.selectConfigFile"
      >
        <span class="mr-3 text-lg">📁</span>
        Add Config
      </button>
    </div>
  </div>
</template>
