// src/components/config/ConfigFileCard.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import { formatLastUpdated } from "../../services/utils";
import { useConfigs } from "../../composables/useConfigs";
import type { ConfigFileEntry, SubscriptionInfo } from "../../types/app";

const props = defineProps<{
  config: ConfigFileEntry;
  isSelected: boolean;
  subscription?: SubscriptionInfo;
  isLoading: boolean;
}>();

const configs = useConfigs();
const isManaging = ref(false);
const newFileName = ref("");
const editingSubscriptionUrl = ref("");

const cardClass = computed(() => {
  if (isManaging.value) {
    return "border-orange-400 bg-orange-50 cursor-default";
  }

  if (props.isSelected) {
    return "border-blue-400 bg-blue-50 shadow-sm";
  }

  return "border-gray-200 hover:-translate-y-0.5 hover:border-gray-300 hover:shadow-sm";
});

function startManage() {
  if (props.isLoading) {
    return;
  }

  isManaging.value = true;
  newFileName.value = props.config.displayName;
  editingSubscriptionUrl.value = props.subscription?.url ?? "";
}

function cancelManage() {
  isManaging.value = false;
  newFileName.value = "";
  editingSubscriptionUrl.value = "";
}

async function saveManage() {
  const nextFileName =
    newFileName.value !== props.config.displayName
      ? newFileName.value
      : props.config.displayName;

  if (newFileName.value !== props.config.displayName) {
    await configs.renameConfig(props.config.displayName, newFileName.value);
  }

  if (editingSubscriptionUrl.value !== (props.subscription?.url ?? "")) {
    await configs.editSubscription(
      nextFileName,
      editingSubscriptionUrl.value,
    );
  }

  cancelManage();
}

function handleKeydown(event: KeyboardEvent) {
  if (event.key === "Enter") {
    void saveManage();
  } else if (event.key === "Escape") {
    cancelManage();
  }
}

function handleSelect() {
  if (isManaging.value) {
    return;
  }

  void configs.selectConfig(props.config);
}
</script>

<template>
  <div
    class="cursor-pointer rounded-lg border bg-white p-4 transition-all duration-300"
    :class="cardClass"
    @click="handleSelect"
  >
    <div v-if="isManaging" class="space-y-4" @click.stop>
      <div>
        <h4 class="mb-0 text-lg font-semibold text-gray-800">
          Edit Configuration
        </h4>
      </div>

      <div class="space-y-2">
        <label class="block text-sm font-medium text-gray-700">File Name</label>
        <input
          v-model="newFileName"
          class="w-full rounded-lg border border-gray-300 px-4 py-2.5 text-sm outline-none transition-all duration-200 focus:border-blue-500 focus:ring-2 focus:ring-blue-200"
          :disabled="isLoading"
          autofocus
          @keydown="handleKeydown"
        />
      </div>

      <div class="space-y-2">
        <label class="block text-sm font-medium text-gray-700">
          Subscription URL
        </label>
        <input
          v-model="editingSubscriptionUrl"
          class="w-full rounded-lg border border-gray-300 px-4 py-2.5 text-sm outline-none transition-all duration-200 focus:border-blue-500 focus:ring-2 focus:ring-blue-200"
          placeholder="Enter subscription URL (optional)"
          :disabled="isLoading"
          @keydown="handleKeydown"
        />
      </div>

      <div class="flex gap-3 pt-2">
        <button
          class="flex items-center gap-2 rounded-lg bg-green-600 px-4 py-2.5 text-sm font-medium text-white transition-all duration-200 hover:-translate-y-0.5 hover:bg-green-700 hover:shadow-sm disabled:cursor-not-allowed disabled:opacity-50"
          :disabled="isLoading"
          @click="saveManage"
        >
          <span class="text-base">✓</span>
          Save
        </button>
        <button
          class="flex items-center gap-2 rounded-lg bg-gray-600 px-4 py-2.5 text-sm font-medium text-white transition-all duration-200 hover:-translate-y-0.5 hover:bg-gray-700 hover:shadow-sm disabled:cursor-not-allowed disabled:opacity-50"
          :disabled="isLoading"
          @click="cancelManage"
        >
          <span class="text-base">✕</span>
          Cancel
        </button>
      </div>
    </div>

    <div v-else class="flex items-center justify-between">
      <div class="min-w-0 grow">
        <div class="mb-1 flex flex-wrap items-center gap-2">
          <span class="shrink-0 text-lg">
            {{ subscription ? "🔗" : "📄" }}
          </span>
          <h4 class="truncate text-sm font-semibold text-gray-800">
            {{ config.displayName }}
          </h4>
          <div
            v-if="subscription"
            class="shrink-0 rounded-full bg-blue-100 px-2 py-0.5 text-xs font-medium text-blue-700"
          >
            Subscription
          </div>
          <div
            v-if="isSelected"
            class="shrink-0 rounded-full bg-green-100 px-2 py-0.5 text-xs font-medium text-green-700"
          >
            Active
          </div>
        </div>

        <div v-if="subscription" class="text-xs text-gray-500">
          {{ formatLastUpdated(subscription.lastUpdated) }}
        </div>
      </div>

      <div class="ml-4 flex shrink-0 gap-1.5">
        <button
          class="flex h-8 w-8 items-center justify-center rounded-md bg-slate-200 text-xs font-medium text-slate-700 transition-all duration-200 hover:bg-slate-300 hover:text-slate-900 disabled:cursor-not-allowed disabled:opacity-50"
          :disabled="isLoading"
          title="Open configuration file"
          @click.stop="configs.openConfigFile(config.displayName)"
        >
          <span class="text-sm">↗</span>
        </button>

        <button
          v-if="subscription"
          class="flex h-8 w-8 items-center justify-center rounded-md bg-emerald-200 text-xs font-medium text-emerald-700 transition-all duration-200 hover:bg-emerald-300 hover:text-emerald-900 disabled:cursor-not-allowed disabled:opacity-50"
          :disabled="isLoading"
          title="Update from subscription"
          @click.stop="configs.updateSubscription(config.displayName)"
        >
          <span class="text-sm">↻</span>
        </button>

        <button
          class="flex h-8 w-8 items-center justify-center rounded-md bg-indigo-200 text-xs font-medium text-indigo-700 transition-all duration-200 hover:bg-indigo-300 hover:text-indigo-900 disabled:cursor-not-allowed disabled:opacity-50"
          :disabled="isLoading"
          title="Edit configuration"
          @click.stop="startManage"
        >
          <span class="text-sm">✎</span>
        </button>

        <button
          class="flex h-8 w-8 items-center justify-center rounded-md bg-rose-200 text-xs font-medium text-rose-700 transition-all duration-200 hover:bg-rose-300 hover:text-rose-900 disabled:cursor-not-allowed disabled:opacity-50"
          :disabled="isLoading"
          title="Delete configuration"
          @click.stop="configs.deleteConfig(config.displayName)"
        >
          <span class="text-sm">✕</span>
        </button>
      </div>
    </div>
  </div>
</template>

// src.old/components/config/ConfigFileCard.tsx
import { useState } from "react";
import {
  Card,
  Text,
  Badge,
  Button,
  Input,
  Spinner,
} from "@fluentui/react-components";
import {
  LinkRegular,
  DocumentRegular,
  OpenRegular,
  ArrowClockwiseRegular,
  EditRegular,
  DeleteRegular,
  CheckmarkRegular,
  DismissRegular,
} from "@fluentui/react-icons";
import { formatLastUpdated } from "../../services/utils";
import { useConfigs } from "../../hooks/useConfigs";
import type { ConfigFileEntry, SubscriptionInfo } from "../../types/app";

interface Props {
  config: ConfigFileEntry;
  isSelected: boolean;
  subscription?: SubscriptionInfo;
  isLoading: boolean;
}

export default function ConfigFileCard({ config, isSelected, subscription, isLoading }: Props) {
  const configs = useConfigs();
  const [isManaging, setIsManaging] = useState(false);
  const [newFileName, setNewFileName] = useState("");
  const [editingSubscriptionUrl, setEditingSubscriptionUrl] = useState("");

  const startManage = (e: React.MouseEvent) => {
    e.stopPropagation();
    if (isLoading) return;
    setIsManaging(true);
    setNewFileName(config.displayName);
    setEditingSubscriptionUrl(subscription?.url ?? "");
  };

  const cancelManage = (e?: React.MouseEvent) => {
    if (e) e.stopPropagation();
    setIsManaging(false);
    setNewFileName("");
    setEditingSubscriptionUrl("");
  };

  const saveManage = async (e?: React.MouseEvent) => {
    if (e) e.stopPropagation();
    const nextFileName =
      newFileName !== config.displayName ? newFileName : config.displayName;

    if (newFileName !== config.displayName) {
      await configs.renameConfig(config.displayName, newFileName);
    }

    if (editingSubscriptionUrl !== (subscription?.url ?? "")) {
      await configs.editSubscription(nextFileName, editingSubscriptionUrl);
    }

    cancelManage();
  };

  const handleKeydown = (event: React.KeyboardEvent) => {
    if (event.key === "Enter") {
      void saveManage();
    } else if (event.key === "Escape") {
      cancelManage();
    }
  };

  const handleSelect = () => {
    if (isManaging || isLoading) return;
    void configs.selectConfig(config);
  };

  if (isManaging) {
    return (
      <Card className="border-brand-500 bg-brand-500/10 cursor-default" onClick={(e) => e.stopPropagation()}>
        <div className="flex flex-col gap-4 p-2">
          <Text size={400} weight="semibold">Edit Configuration</Text>
          
          <div className="flex flex-col gap-1">
            <Text size={200} weight="medium">File Name</Text>
            <Input
              value={newFileName}
              onChange={(_, data) => setNewFileName(data.value)}
              disabled={isLoading}
              onKeyDown={handleKeydown}
              autoFocus
            />
          </div>

          <div className="flex flex-col gap-1">
            <Text size={200} weight="medium">Subscription URL</Text>
            <Input
              value={editingSubscriptionUrl}
              onChange={(_, data) => setEditingSubscriptionUrl(data.value)}
              placeholder="Enter subscription URL (optional)"
              disabled={isLoading}
              onKeyDown={handleKeydown}
            />
          </div>

          <div className="flex gap-2">
            <Button
              appearance="primary"
              icon={isLoading ? <Spinner size="extra-tiny" /> : <CheckmarkRegular />}
              disabled={isLoading}
              onClick={saveManage}
            >
              Save
            </Button>
            <Button
              appearance="secondary"
              icon={<DismissRegular />}
              disabled={isLoading}
              onClick={cancelManage}
            >
              Cancel
            </Button>
          </div>
        </div>
      </Card>
    );
  }

  return (
    <Card
      className={`cursor-pointer transition-all duration-200 ${
        isSelected ? "border-brand-500 bg-brand-500/10" : "border-neutral-700 bg-neutral-800 hover:border-neutral-500"
      }`}
      onClick={handleSelect}
    >
      <div className="flex items-center justify-between p-1">
        <div className="flex flex-col min-w-0 grow gap-1">
          <div className="flex flex-wrap items-center gap-2">
            {subscription ? <LinkRegular /> : <DocumentRegular />}
            <Text weight="semibold" className="truncate max-w-[150px]" title={config.displayName}>
              {config.displayName}
            </Text>
            {subscription && (
              <Badge color="informative" shape="rounded" appearance="tint">
                Subscription
              </Badge>
            )}
            {isSelected && (
              <Badge color="success" shape="rounded" appearance="tint">
                Active
              </Badge>
            )}
          </div>
          {subscription && (
            <Text size={200} className="text-neutral-500">
              {formatLastUpdated(subscription.lastUpdated)}
            </Text>
          )}
        </div>

        <div className="flex items-center shrink-0 gap-1 ml-2">
          <Button
            appearance="subtle"
            icon={<OpenRegular />}
            disabled={isLoading}
            onClick={(e) => {
              e.stopPropagation();
              void configs.openConfigFile(config.displayName);
            }}
            title="Open configuration file"
          />
          {subscription && (
            <Button
              appearance="subtle"
              icon={<ArrowClockwiseRegular />}
              disabled={isLoading}
              onClick={(e) => {
                e.stopPropagation();
                void configs.updateSubscription(config.displayName);
              }}
              title="Update from subscription"
            />
          )}
          <Button
            appearance="subtle"
            icon={<EditRegular />}
            disabled={isLoading}
            onClick={startManage}
            title="Edit configuration"
          />
          <Button
            appearance="subtle"
            icon={<DeleteRegular className="text-red-500" />}
            disabled={isLoading}
            onClick={(e) => {
              e.stopPropagation();
              void configs.deleteConfig(config.displayName);
            }}
            title="Delete configuration"
          />
        </div>
      </div>
    </Card>
  );
}
