// src.old/components/Custom.tsx
import { Text } from "@fluentui/react-components";
import ConfigOverrideSection from "./settings/ConfigOverrideSection";
import LogSettingsSection from "./settings/LogSettingsSection";
import { useSettings } from "../hooks/useSettings";

export default function Custom() {
  const settings = useSettings({ loadCustomerSettings: true });

  return (
    <div className="flex flex-col gap-4 h-full overflow-hidden pb-4">
      <div className="flex items-center justify-between">
        <Text size={600} weight="semibold">Custom</Text>
      </div>

      <div className="flex flex-col gap-6 h-full min-h-0 overflow-y-auto pr-2">
        <LogSettingsSection
          isLoading={settings.isLoading}
          enableTransitions={settings.enableTransitions}
          selectedStackOption={settings.selectedStackOption}
          stackOptions={settings.stackOptions}
          hasStackField={settings.hasStackField}
          logDisabled={settings.logDisabled}
          selectedLogLevel={settings.selectedLogLevel}
          logLevels={settings.logLevels}
          hasLogField={settings.hasLogField}
          onSetStackOption={settings.setStackOption}
          onLogDisabledChange={settings.toggleLogDisabled}
          onSetLogLevel={settings.setLogLevel}
        />

        <ConfigOverrideSection
          enabled={settings.isOverrideEnabled}
          onEnabledChange={settings.setOverrideEnabled}
          config={settings.overrideConfig}
          onConfigChange={settings.setOverrideConfig}
          isValidJson={settings.isValidJson}
          jsonError={settings.jsonError}
          onSave={() => void settings.saveOverride()}
          onClear={() => void settings.clearOverride()}
        />
      </div>
    </div>
  );
}

// src/components/Custom.vue
<script setup lang="ts">
import ConfigOverrideSection from "./settings/ConfigOverrideSection.vue";
import LogSettingsSection from "./settings/LogSettingsSection.vue";
import { useSettings } from "../composables/useSettings";

const settings = useSettings({ loadCustomerSettings: true });
</script>

<template>
  <div class="content-card">
    <div class="card-header">
      <h2>Custom</h2>
    </div>

    <div class="card-content">
      <LogSettingsSection
        :is-loading="settings.isLoading.value"
        :enable-transitions="settings.enableTransitions.value"
        :selected-stack-option="settings.selectedStackOption.value"
        :stack-options="settings.stackOptions"
        :has-stack-field="settings.hasStackField.value"
        :log-disabled="settings.logDisabled.value"
        :selected-log-level="settings.selectedLogLevel.value"
        :log-levels="settings.logLevels"
        :has-log-field="settings.hasLogField.value"
        @set-stack-option="settings.setStackOption"
        @update:log-disabled="settings.logDisabled.value = $event"
        @set-log-level="settings.setLogLevel"
        @update-log-configuration="settings.updateLogConfiguration"
      />

      <ConfigOverrideSection
        v-model:enabled="settings.isOverrideEnabled.value"
        v-model:config="settings.overrideConfig.value"
        :is-valid-json="settings.isValidJson.value"
        :json-error="settings.jsonError.value"
        @save="settings.saveOverride"
        @clear="settings.clearOverride"
      />
    </div>
  </div>
</template>
