// src/pages/Logs/index.tsx
import {
  ArrowDownloadRegular,
  DismissRegular,
  PauseRegular,
  PlayRegular,
  SearchRegular,
} from "@fluentui/react-icons";
import { useVirtualizer } from "@tanstack/react-virtual";
import { useEffect, useRef } from "react";
import { Button } from "../../components/ui/Button";
import { PageHeader } from "../../components/ui/PageHeader";
import { useLogsStream } from "../../hooks/useLogsStream";

const LEVEL_COLORS: Record<string, string> = {
  panic: "text-(--wb-log-panic)",
  fatal: "text-(--wb-log-fatal)",
  error: "text-(--wb-log-error)",
  warn: "text-(--wb-log-warn)",
  warning: "text-(--wb-log-warn)",
  info: "text-(--wb-log-info)",
  debug: "text-(--wb-log-debug)",
  trace: "text-(--wb-log-trace)",
};

const LOG_LEVELS = [
  "panic",
  "fatal",
  "error",
  "warn",
  "info",
  "debug",
  "trace",
] as const;

export default function Logs() {
  const {
    visibleLogs,
    isPaused,
    search,
    typeFilter,
    logLevel,
    logLevels,
    streamStatus,
    setSearch,
    setTypeFilter,
    setIsPaused,
    setLogLevel,
    clearLogs,
    downloadLogs,
    startStream,
    restartStream,
  } = useLogsStream();
  const listRef = useRef<HTMLDivElement>(null);

  const rowVirtualizer = useVirtualizer({
    count: visibleLogs.length,
    getScrollElement: () => listRef.current,
    estimateSize: () => 30,
    measureElement: (element) => element.getBoundingClientRect().height,
    overscan: 8,
  });

  useEffect(() => {
    startStream();
  }, [startStream]);

  return (
    <div className="flex flex-col h-full overflow-hidden">
      <div className="shrink-0 pr-2">
        <PageHeader
          title="Logs"
          description="Real-time core diagnostic output and connection events."
        >
          <div className="flex items-center gap-2">
            <Button
              icon={isPaused ? <PlayRegular /> : <PauseRegular />}
              variant="subtle"
              onClick={() => setIsPaused(!isPaused)}
            >
              {isPaused ? "Resume" : "Pause"}
            </Button>
            <Button
              icon={<ArrowDownloadRegular />}
              variant="subtle"
              onClick={downloadLogs}
            >
              Export
            </Button>
            <Button icon={<DismissRegular />} variant="subtle" onClick={clearLogs}>
              Clear
            </Button>
          </div>
        </PageHeader>
      </div>

      <div className="flex flex-col gap-4 h-full min-h-0 pr-2 pb-10">
        <div className="flex items-center gap-3 flex-wrap">
          <div className="flex items-center gap-2 px-3 py-1.5 rounded-(--wb-radius-md) border border-(--wb-border-default) bg-(--wb-surface-layer) w-64">
            <SearchRegular className="text-(--wb-text-tertiary) text-sm" />
            <input
              value={search}
              onChange={(event) => setSearch(event.target.value)}
              placeholder="Search logs..."
              className="flex-1 bg-transparent text-sm outline-none text-(--wb-text-primary) placeholder:text-(--wb-text-disabled)"
            />
          </div>

          <div className="flex items-center gap-2">
            <span className="text-sm font-medium text-(--wb-text-secondary)">
              Stream Level:
            </span>
            <select
              value={logLevel}
              onChange={(event) => {
                void setLogLevel(event.target.value as typeof logLevel).then(() => {
                  restartStream();
                });
              }}
              disabled={streamStatus === "disabled"}
              className="px-3 py-1.5 text-sm rounded-(--wb-radius-md) border border-(--wb-border-default) bg-(--wb-surface-layer) text-(--wb-text-primary) outline-none focus:border-(--wb-accent) disabled:opacity-40 disabled:cursor-not-allowed"
              title="Stream log level"
            >
              {logLevels.map((level) => (
                <option key={level} value={level}>
                  {level}
                </option>
              ))}
            </select>
          </div>

          <div className="flex-1" />

          <div className="flex gap-1.5 bg-(--wb-surface-layer) p-1 rounded-(--wb-radius-md) border border-(--wb-border-subtle) winui-segmented-control">
            {LOG_LEVELS.map((level) => (
              <button
                key={level}
                onClick={() => setTypeFilter(typeFilter === level ? "" : level)}
                className={[
                  "px-3 py-1 text-xs font-semibold uppercase tracking-wider rounded transition-colors",
                  typeFilter === level
                    ? "bg-(--wb-surface-hover) text-(--wb-text-primary)"
                    : "text-(--wb-text-secondary) hover:text-(--wb-text-primary)",
                ].join(" ")}
              >
                {level}
              </button>
            ))}
          </div>
        </div>

        <div className="flex-1 min-h-0 rounded-xl border border-(--wb-border-subtle) bg-(--wb-log-bg) shadow-inner p-3 font-mono">
          {streamStatus === "disabled" ? (
            <div className="flex flex-col items-center justify-center h-full gap-2 text-(--wb-text-disabled) text-sm font-medium">
              <span>Log output is disabled in the core configuration.</span>
              <span className="text-xs text-(--wb-text-disabled) opacity-60">
                Enable it in Settings → Core Log Level.
              </span>
            </div>
          ) : visibleLogs.length === 0 ? (
            <div className="flex items-center justify-center h-full text-(--wb-text-disabled) text-sm font-medium">
              No logs available
            </div>
          ) : (
            <div ref={listRef} className="h-full w-full overflow-auto custom-scrollbar">
              <div
                style={{
                  minWidth: "100%",
                  display: "inline-block",
                }}
              >
                <div style={{ height: rowVirtualizer.getVirtualItems().length > 0 ? rowVirtualizer.getVirtualItems()[0].start : 0 }} />
                {rowVirtualizer.getVirtualItems().map((virtualRow) => {
                  const entry = visibleLogs[virtualRow.index];
                  return (
                    <div
                      key={entry.seq}
                      ref={rowVirtualizer.measureElement}
                      className={[
                        "py-1 px-2 hover:bg-(--wb-surface-hover) rounded group transition-colors",
                        LEVEL_COLORS[entry.type] ?? "text-(--wb-text-primary)",
                        virtualRow.index % 2 === 0 ? "bg-(--wb-surface-active)" : "",
                      ].join(" ")}
                    >
                      <div className="flex items-start gap-3">
                        <span className="shrink-0 text-(--wb-text-disabled) font-semibold w-12 text-right tracking-wider">
                          {entry.type.toUpperCase().slice(0, 5)}
                        </span>
                        {entry.time && (
                          <span className="shrink-0 text-(--wb-text-tertiary) w-20">
                            {entry.time}
                          </span>
                        )}
                        <span
                          className="flex-1 whitespace-pre text-[13px] leading-5"
                          title={entry.payload}
                        >
                          {entry.payload}
                        </span>
                      </div>
                    </div>
                  );
                })}
                <div style={{ height: rowVirtualizer.getVirtualItems().length > 0 ? rowVirtualizer.getTotalSize() - rowVirtualizer.getVirtualItems()[rowVirtualizer.getVirtualItems().length - 1].end : 0 }} />
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

// src/components/Logs.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, watch } from "vue";
import { useLogsStream } from "../composables/useLogsStream";
import { useAppStore } from "../stores/appStore";

const appStore = useAppStore();
const logs = useLogsStream();

const statusLabel = computed(() => {
  if (!appStore.isRunning.value) {
    return "Service stopped";
  }
  if (logs.streamStatus.value === "connected") {
    return "Streaming";
  }
  if (logs.streamStatus.value === "connecting") {
    return "Connecting";
  }
  if (logs.streamStatus.value === "error") {
    return "Error";
  }
  return "Disconnected";
});

const logBadgeClass = (type: string) => {
  switch (type) {
    case "trace":
      return "bg-slate-100 text-slate-700";
    case "debug":
      return "bg-violet-100 text-violet-700";
    case "info":
      return "bg-blue-100 text-blue-700";
    case "warn":
    case "warning":
      return "bg-amber-100 text-amber-700";
    default:
      return "bg-rose-100 text-rose-700";
  }
};

onMounted(() => {
  if (appStore.isRunning.value) {
    logs.startStream();
  }
});

watch(
  () => appStore.isRunning.value,
  (running) => {
    if (running) {
      logs.startStream();
    } else {
      logs.stopStream(true);
    }
  },
);

watch(
  () => logs.logLevel.value,
  () => {
    if (appStore.isRunning.value) {
      logs.restartStream();
    }
  },
);

onBeforeUnmount(() => {
  logs.stopStream(false);
});
</script>

<template>
  <div class="content-card">
    <div class="card-header">
      <div class="flex flex-wrap items-start justify-between gap-4">
        <div>
          <h2>Logs</h2>
          <p class="mt-1 text-sm text-gray-500">
            实时日志流、级别筛选、类别筛选、暂停、清空和导出。
          </p>
        </div>

        <div class="flex flex-wrap items-center gap-2">
          <span
            class="rounded-full px-3 py-1 text-xs font-semibold"
            :class="
              statusLabel === 'Streaming'
                ? 'bg-emerald-100 text-emerald-700'
                : statusLabel === 'Connecting'
                  ? 'bg-amber-100 text-amber-700'
                  : statusLabel === 'Error'
                    ? 'bg-rose-100 text-rose-700'
                    : 'bg-slate-100 text-slate-600'
            "
          >
            {{ statusLabel }}
          </span>
          <button
            class="rounded-lg bg-slate-200 px-4 py-2 text-sm font-medium text-slate-700 transition-all duration-200 hover:bg-slate-300 disabled:cursor-not-allowed disabled:opacity-50"
            :disabled="!appStore.isRunning.value"
            @click="logs.isPaused.value = !logs.isPaused.value"
          >
            {{ logs.isPaused.value ? "Resume" : "Pause" }}
          </button>
          <button
            class="rounded-lg bg-slate-200 px-4 py-2 text-sm font-medium text-slate-700 transition-all duration-200 hover:bg-slate-300"
            @click="logs.downloadLogs"
          >
            Export
          </button>
          <button
            class="rounded-lg bg-rose-600 px-4 py-2 text-sm font-medium text-white transition-all duration-200 hover:bg-rose-700"
            @click="logs.clearLogs"
          >
            Clear
          </button>
        </div>
      </div>
    </div>

    <div class="card-content flex min-h-0 flex-col gap-4">
      <div
        v-if="!appStore.isRunning.value"
        class="rounded-xl border border-dashed border-gray-300 bg-gray-50 px-5 py-6 text-sm text-gray-500"
      >
        Start sing-box first, then open Logs to inspect the live core output.
      </div>

      <template v-else>
        <div class="rounded-xl border border-gray-200 bg-white p-4 shadow-sm">
          <div class="flex flex-wrap items-center gap-3">
            <select
              v-model="logs.logLevel.value"
              class="rounded-lg border border-gray-300 bg-white px-3 py-2.5 text-sm text-gray-700 outline-none transition-all duration-200 focus:border-blue-500 focus:ring-2 focus:ring-blue-200"
            >
              <option v-for="level in logs.logLevels" :key="level" :value="level">
                {{ level }}
              </option>
            </select>

            <select
              v-model="logs.typeFilter.value"
              class="rounded-lg border border-gray-300 bg-white px-3 py-2.5 text-sm text-gray-700 outline-none transition-all duration-200 focus:border-blue-500 focus:ring-2 focus:ring-blue-200"
            >
              <option value="">All categories</option>
              <option v-for="type in logs.availableTypes.value" :key="type" :value="type">
                {{ type }}
              </option>
            </select>

            <input
              v-model="logs.search.value"
              type="text"
              class="min-w-64 flex-1 rounded-lg border border-gray-300 px-4 py-2.5 text-sm outline-none transition-all duration-200 focus:border-blue-500 focus:ring-2 focus:ring-blue-200"
              placeholder="Search time / level / category / payload"
            />
          </div>
        </div>

        <div
          v-if="logs.streamError.value"
          class="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700"
        >
          {{ logs.streamError.value }}
        </div>

        <div class="min-h-0 grow overflow-hidden rounded-xl border border-gray-200 bg-white shadow-sm">
          <div class="max-h-full overflow-y-auto">
            <div
              v-for="entry in logs.visibleLogs.value"
              :key="entry.seq"
              class="border-b border-gray-100 px-4 py-3 transition-all duration-200 hover:bg-gray-50"
            >
              <div class="flex flex-wrap items-center gap-2">
                <span class="text-xs font-semibold tabular-nums text-gray-400">
                  #{{ entry.seq.toString().padStart(4, "0") }}
                </span>
                <span
                  class="rounded-full px-2 py-0.5 text-xs font-semibold"
                  :class="logBadgeClass(entry.type)"
                >
                  {{ entry.type }}
                </span>
                <span class="rounded-full bg-slate-100 px-2 py-0.5 text-xs text-slate-600">
                  {{ entry.category }}
                </span>
                <span class="ml-auto text-xs tabular-nums text-gray-400">
                  {{ entry.time }}
                </span>
              </div>
              <pre class="mt-2 overflow-x-auto whitespace-pre-wrap break-words text-sm leading-6 text-gray-800">{{
                entry.payload
              }}</pre>
            </div>

            <div
              v-if="logs.visibleLogs.value.length === 0"
              class="flex h-64 items-center justify-center px-6 text-center text-sm text-gray-500"
            >
              No logs matched the current filters.
            </div>
          </div>
        </div>
      </template>
    </div>
  </div>
</template>
