// src/components/Overview.vue
<script setup lang="ts">
import { computed } from "vue";
import { useSingbox } from "../composables/useSingbox";
import { useAppStore } from "../stores/appStore";

const appStore = useAppStore();
const singbox = useSingbox();

const isSubscription = computed(() => {
  const displayName = appStore.selectedConfigDisplay.value;
  return !!(displayName && appStore.subscriptions.value[displayName]);
});
</script>

<template>
  <div class="content-card">
    <div class="card-header">
      <h2>Overview</h2>
    </div>
    <div class="card-content">
      <div
        class="overview-status-card"
        :class="{ running: appStore.isRunning.value }"
      >
        <div class="status-header">
          <div class="status-icon-wrapper">
            <div
              class="status-icon"
              :class="{ active: appStore.isRunning.value }"
            >
              <svg
                v-if="appStore.isRunning.value"
                class="h-6 w-6"
                fill="currentColor"
                viewBox="0 0 20 20"
              >
                <path
                  fill-rule="evenodd"
                  d="M10 18a8 8 0 100-16 8 8 0 000 16zM9.555 7.168A1 1 0 008 8v4a1 1 0 001.555.832l3-2a1 1 0 000-1.664l-3-2z"
                  clip-rule="evenodd"
                />
              </svg>
              <svg
                v-else
                class="h-6 w-6"
                fill="currentColor"
                viewBox="0 0 20 20"
              >
                <path
                  fill-rule="evenodd"
                  d="M10 18a8 8 0 100-16 8 8 0 000 16zM8 7a1 1 0 00-1 1v4a1 1 0 001 1h4a1 1 0 001-1V8a1 1 0 00-1-1H8z"
                  clip-rule="evenodd"
                />
              </svg>
            </div>
          </div>
          <div class="status-content">
            <h3 class="status-title">
              {{
                appStore.isRunning.value ? "Service Running" : "Service Stopped"
              }}
            </h3>
            <p class="status-subtitle">
              {{
                appStore.isRunning.value
                  ? "Sing-box is active and ready"
                  : "Click start to begin"
              }}
            </p>
          </div>
          <div
            class="status-badge"
            :class="{
              active: appStore.isRunning.value,
              clickable: appStore.isRunning.value,
            }"
            @click="appStore.isRunning.value ? singbox.openPanel() : null"
          >
            {{ appStore.isRunning.value ? "PANEL" : "INACTIVE" }}
          </div>
        </div>

        <div
          v-if="appStore.selectedConfigDisplay.value"
          class="status-config-info"
        >
          <div class="config-info-left">
            <svg
              v-if="isSubscription"
              class="config-info-icon subscription"
              fill="currentColor"
              viewBox="0 0 20 20"
            >
              <path
                d="M3 4a1 1 0 011-1h12a1 1 0 011 1v2a1 1 0 01-1 1H4a1 1 0 01-1-1V4zM3 10a1 1 0 011-1h6a1 1 0 011 1v6a1 1 0 01-1 1H4a1 1 0 01-1-1v-6zM14 9a1 1 0 00-1 1v6a1 1 0 001 1h2a1 1 0 001-1v-6a1 1 0 00-1-1h-2z"
              />
            </svg>
            <svg
              v-else
              class="config-info-icon"
              fill="currentColor"
              viewBox="0 0 20 20"
            >
              <path
                fill-rule="evenodd"
                d="M4 4a2 2 0 012-2h4.586A2 2 0 0112 2.586L15.414 6A2 2 0 0116 7.414V16a2 2 0 01-2 2H6a2 2 0 01-2-2V4zm2 6a1 1 0 011-1h6a1 1 0 110 2H7a1 1 0 01-1-1zm1 3a1 1 0 100 2h6a1 1 0 100-2H7z"
                clip-rule="evenodd"
              />
            </svg>
            <span class="config-info-text">
              {{ appStore.selectedConfigDisplay.value }}
            </span>
          </div>
          <span
            class="config-info-label"
            :class="{ subscription: isSubscription }"
          >
            {{ isSubscription ? "Subscription" : "Local" }}
          </span>
        </div>
      </div>

      <div class="overview-actions">
        <button
          class="overview-btn start-btn"
          :disabled="
            appStore.isRunning.value ||
            appStore.isLoading.value ||
            !appStore.selectedConfigPath.value
          "
          @click="singbox.startService"
        >
          <svg class="mr-2 h-4 w-4" fill="currentColor" viewBox="0 0 20 20">
            <path
              fill-rule="evenodd"
              d="M10 18a8 8 0 100-16 8 8 0 000 16zM9.555 7.168A1 1 0 008 8v4a1 1 0 001.555.832l3-2a1 1 0 000-1.664l-3-2z"
              clip-rule="evenodd"
            />
          </svg>
          {{
            appStore.isLoading.value && !appStore.isRunning.value
              ? "Starting..."
              : "Start"
          }}
        </button>
        <button
          class="overview-btn stop-btn"
          :disabled="!appStore.isRunning.value || appStore.isLoading.value"
          @click="singbox.stopService"
        >
          <svg class="mr-2 h-4 w-4" fill="currentColor" viewBox="0 0 20 20">
            <path
              fill-rule="evenodd"
              d="M10 18a8 8 0 100-16 8 8 0 000 16zM8 7a1 1 0 00-1 1v4a1 1 0 001 1h4a1 1 0 001-1V8a1 1 0 00-1-1H8z"
              clip-rule="evenodd"
            />
          </svg>
          {{
            appStore.isLoading.value && appStore.isRunning.value
              ? "Stopping..."
              : "Stop"
          }}
        </button>
      </div>
    </div>
  </div>
</template>

// src/components/Overview.tsx
import { useMemo } from "react";
import {
  Card,
  Text,
  Button,
  Badge,
  makeStyles,
  shorthands,
} from "@fluentui/react-components";
import {
  PlayRegular,
  StopRegular,
  DocumentRegular,
  CloudArrowDownRegular,
  OpenRegular,
  CheckmarkCircleRegular,
  ErrorCircleRegular,
} from "@fluentui/react-icons";
import { useAppStore } from "../stores/appStore";
import { useSingbox } from "../hooks/useSingbox";

const useStyles = makeStyles({
  container: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
    height: "100%",
  },
  card: {
    maxWidth: "400px",
  },
  statusHeader: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  statusIcon: {
    fontSize: "32px",
  },
  statusContent: {
    display: "flex",
    flexDirection: "column",
    flexGrow: 1,
  },
  configInfo: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    ...shorthands.padding("12px"),
    backgroundColor: "rgba(0, 0, 0, 0.2)",
    ...shorthands.borderRadius("6px"),
    marginTop: "16px",
  },
  configInfoLeft: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  actions: {
    display: "flex",
    gap: "8px",
    marginTop: "16px",
  },
});

export default function Overview() {
  const styles = useStyles();
  const isRunning = useAppStore((state) => state.isRunning);
  const pendingOperations = useAppStore((state) => state.pendingOperations);
  const selectedConfigDisplay = useAppStore((state) => state.appSettings.app.selected_config_display);
  const selectedConfigPath = useAppStore((state) => state.appSettings.app.selected_config_path);
  const subscriptions = useAppStore((state) => state.subscriptions);
  
  const { startService, stopService, openPanel } = useSingbox();

  const isLoading = pendingOperations > 0;
  const isSubscription = useMemo(() => {
    return !!(selectedConfigDisplay && subscriptions[selectedConfigDisplay]);
  }, [selectedConfigDisplay, subscriptions]);

  return (
    <div className={styles.container}>
      <Text size={600} weight="semibold">Overview</Text>
      
      <Card className={styles.card}>
        <div className={styles.statusHeader}>
          <div className={styles.statusIcon} style={{ color: isRunning ? "var(--colorPaletteGreenForeground1)" : "var(--colorNeutralForeground3)" }}>
            {isRunning ? <CheckmarkCircleRegular /> : <ErrorCircleRegular />}
          </div>
          <div className={styles.statusContent}>
            <Text weight="semibold" size={400}>
              {isRunning ? "Service Running" : "Service Stopped"}
            </Text>
            <Text size={200} className="opacity-70">
              {isRunning ? "Sing-box is active and ready" : "Click start to begin"}
            </Text>
          </div>
          <Badge
            color={isRunning ? "success" : "subtle"}
            appearance={isRunning ? "filled" : "ghost"}
            onClick={isRunning ? openPanel : undefined}
            icon={isRunning ? <OpenRegular /> : undefined}
            style={{ cursor: isRunning ? "pointer" : "default" }}
          >
            {isRunning ? "PANEL" : "INACTIVE"}
          </Badge>
        </div>

        {selectedConfigDisplay && (
          <div className={styles.configInfo}>
            <div className={styles.configInfoLeft}>
              {isSubscription ? <CloudArrowDownRegular /> : <DocumentRegular />}
              <Text truncate>{selectedConfigDisplay}</Text>
            </div>
            <Badge appearance="outline" color={isSubscription ? "brand" : "subtle"}>
              {isSubscription ? "Subscription" : "Local"}
            </Badge>
          </div>
        )}

        <div className={styles.actions}>
          <Button
            appearance="primary"
            icon={<PlayRegular />}
            disabled={isRunning || isLoading || !selectedConfigPath}
            onClick={startService}
          >
            {isLoading && !isRunning ? "Starting..." : "Start"}
          </Button>
          <Button
            icon={<StopRegular />}
            disabled={!isRunning || isLoading}
            onClick={stopService}
          >
            {isLoading && isRunning ? "Stopping..." : "Stop"}
          </Button>
        </div>
      </Card>
    </div>
  );
}
