// src/components/Settings.vue
<script setup lang="ts">
import ProcessManager from "./settings/ProcessManager.vue";
import SingboxCoreSection from "./settings/SingboxCoreSection.vue";
import { useSettings } from "../composables/useSettings";

const settings = useSettings({ loadCustomerSettings: false });
</script>

<template>
  <div class="content-card">
    <div class="card-header">
      <h2>Settings</h2>
    </div>

    <div class="card-content">
      <SingboxCoreSection
        :core-status="settings.coreStatus.value"
        :core-status-error="settings.coreStatusError.value"
        :core-status-text="settings.coreStatusText.value"
        :core-status-badge-class="settings.coreStatusBadgeClass.value"
        :is-refreshing-core-status="settings.isRefreshingCoreStatus.value"
        :is-updating-core="settings.isUpdatingCore.value"
        :update-core-button-label="settings.updateCoreButtonLabel.value"
        @refresh="settings.refreshCoreStatus(true)"
        @update="settings.installCoreUpdate"
      />

      <div class="settings-section">
        <h3>Open Directory</h3>
        <div class="setting-item border-b-0!">
          <button
            class="control-button flex items-center gap-2 bg-gray-500 text-white hover:bg-gray-600"
            @click="settings.openApplicationDirectory"
          >
            <span class="text-base">📁</span>
            Open App Directory
          </button>
        </div>
      </div>

      <ProcessManager
        :is-refreshing="settings.isRefreshing.value"
        :is-getting-status="settings.isGettingStatus.value"
        :process-status="settings.processStatus.value"
        :process-status-class="settings.processStatusClass.value"
        @refresh="settings.detectManagedProcess"
        @get-status="settings.loadManagedProcessStatus"
      />
    </div>
  </div>
</template>

// src/components/Settings.tsx
import { Text, Card, Button } from "@fluentui/react-components";
import { FolderOpenRegular } from "@fluentui/react-icons";
import ProcessManager from "./settings/ProcessManager";
import SingboxCoreSection from "./settings/SingboxCoreSection";
import { useSettings } from "../hooks/useSettings";
import { useAppStore } from "../stores/appStore";

export default function Settings() {
  const appStore = useAppStore();
  const settings = useSettings({
    loadCustomerSettings: false,
    autoRefreshCoreStatus: true,
  });

  return (
    <div className="flex flex-col gap-4 h-full overflow-hidden pb-4">
      <div className="flex items-center justify-between">
        <Text size={600} weight="semibold">Settings</Text>
      </div>

      <div className="flex flex-col gap-6 h-full min-h-0 overflow-y-auto pr-2">
        <SingboxCoreSection
          coreStatus={settings.coreStatus}
          coreStatusError={settings.coreStatusError}
          coreUpdateProgress={settings.coreUpdateProgress}
          currentCoreLabel={settings.currentCoreLabel}
          selectedCoreLabel={settings.selectedCoreLabel}
          selectedCoreOptionKey={settings.selectedCoreOptionKey}
          availableOptions={settings.coreStatus?.available_options ?? []}
          coreStatusText={settings.coreStatusText}
          coreStatusBadgeClass={settings.coreStatusBadgeClass}
          isRefreshingCoreStatus={settings.isRefreshingCoreStatus}
          isUpdatingCore={settings.isUpdatingCore}
          updateCoreButtonLabel={settings.updateCoreButtonLabel}
          onRefresh={() => void settings.refreshCoreStatus(true, true)}
          onApply={() => void settings.applySelectedCore()}
          onSelectedCoreOptionKeyChange={(val) => {
            void appStore.setSelectedCoreOptionKey(val);
          }}
        />

        <Card className="flex flex-col gap-4 p-4 bg-neutral-800">
          <Text size={500} weight="semibold">Open Directory</Text>
          <div className="flex">
            <Button
              appearance="secondary"
              icon={<FolderOpenRegular />}
              onClick={() => void settings.openApplicationDirectory()}
            >
              Open App Directory
            </Button>
          </div>
        </Card>

        <ProcessManager
          isRefreshingStatus={settings.isRefreshingStatus}
          processStatus={settings.processStatus}
          processStatusClass={settings.processStatusClass}
          onRefresh={() => void settings.refreshManagedProcessStatus()}
        />
      </div>
    </div>
  );
}
