// src/components/settings/ProcessManager.vue
<script setup lang="ts">
import { computed } from "vue";

const props = defineProps<{
  isRefreshingStatus: boolean;
  processStatus: string;
  processStatusClass: string;
}>();

defineEmits<{
  refresh: [];
}>();

const statusTextClass = computed(() => {
  if (props.processStatusClass === "status-success") {
    return "border-green-500 bg-green-50 text-green-800";
  }

  if (props.processStatusClass === "status-error") {
    return "border-red-500 bg-red-50 text-red-800";
  }

  return "border-blue-500 bg-blue-50 text-blue-800";
});
</script>

<template>
  <div class="settings-section">
    <h3>Process Management</h3>
    <div class="flex flex-col gap-4">
      <div class="flex flex-wrap gap-3">
        <button
          class="control-button min-w-40 flex-1 rounded-lg border-0 px-4 py-3 text-sm font-medium text-white shadow-sm transition-all duration-200"
          :class="
            isRefreshingStatus
              ? 'cursor-not-allowed bg-gray-300 text-gray-500 shadow-none'
              : 'bg-blue-500 hover:bg-blue-600 hover:shadow-sm config-button-hover'
          "
          :disabled="isRefreshingStatus"
          @click="$emit('refresh')"
        >
          <span
            v-if="isRefreshingStatus"
            class="flex h-5 w-5 items-center justify-center text-base animate-spin"
            >🔄</span
          >
          <span
            v-else
            class="flex h-5 w-5 items-center justify-center text-base"
            >📊</span
          >
          <span class="font-medium">
            {{ isRefreshingStatus ? "Refreshing..." : "Refresh Status" }}
          </span>
        </button>
      </div>

      <div
        v-if="processStatus"
        class="overflow-hidden rounded-xl border border-gray-200 bg-white shadow-sm transition-all duration-200 hover:shadow-md"
      >
        <div
          class="flex items-center gap-2 border-b border-gray-200 bg-gray-50 px-4 py-3"
        >
          <span
            class="flex h-6 w-6 items-center justify-center rounded-full text-base"
          >
            <span v-if="processStatusClass === 'status-success'">✅</span>
            <span v-else-if="processStatusClass === 'status-error'">❌</span>
            <span v-else>ℹ️</span>
          </span>
          <span class="text-sm font-semibold text-gray-800"
            >Process Status</span
          >
        </div>
        <div class="p-4">
          <p
            class="m-0 rounded-md border-l-4 p-3 text-sm font-medium leading-relaxed"
            :class="statusTextClass"
          >
            {{ processStatus }}
          </p>
        </div>
      </div>
    </div>
  </div>
</template>

// src/components/settings/ProcessManager.tsx
import {
  Text,
  Card,
  Button,
  Spinner,
} from "@fluentui/react-components";
import { ArrowClockwiseRegular, CheckmarkCircleRegular, ErrorCircleRegular, InfoRegular } from "@fluentui/react-icons";

interface Props {
  isRefreshingStatus: boolean;
  processStatus: string;
  processStatusClass: string;
  onRefresh: () => void;
}

export default function ProcessManager({
  isRefreshingStatus,
  processStatus,
  processStatusClass,
  onRefresh,
}: Props) {
  const getStatusIcon = () => {
    if (processStatusClass === "status-success" || processStatusClass === "text-green-500") {
      return <CheckmarkCircleRegular className="text-green-500" />;
    }
    if (processStatusClass === "status-error" || processStatusClass === "text-red-500") {
      return <ErrorCircleRegular className="text-red-500" />;
    }
    return <InfoRegular className="text-blue-500" />;
  };

  return (
    <Card className="flex flex-col gap-4 p-4 bg-neutral-800">
      <Text size={500} weight="semibold">Process Management</Text>

      <div className="flex flex-col gap-4">
        <div className="flex flex-wrap gap-3">
          <Button
            appearance="primary"
            icon={isRefreshingStatus ? <Spinner size="extra-tiny" /> : <ArrowClockwiseRegular />}
            disabled={isRefreshingStatus}
            onClick={onRefresh}
          >
            {isRefreshingStatus ? "Refreshing..." : "Refresh Status"}
          </Button>
        </div>

        {processStatus && (
          <div className="rounded-xl border border-neutral-700 bg-neutral-900 shadow-sm overflow-hidden">
            <div className="flex items-center gap-2 border-b border-neutral-700 bg-neutral-800 px-4 py-3">
              <span className="flex h-6 w-6 items-center justify-center text-base">
                {getStatusIcon()}
              </span>
              <Text weight="semibold" className="text-neutral-300">
                Process Status
              </Text>
            </div>
            <div className="p-4">
              <Text
                className={`block rounded-md border-l-4 p-3 text-sm font-medium leading-relaxed bg-neutral-800 ${processStatusClass}`}
                style={{
                  borderLeftColor: processStatusClass.includes('green') ? 'var(--colorPaletteGreenForeground1)' : processStatusClass.includes('red') ? 'var(--colorPaletteRedForeground1)' : 'var(--colorPaletteBlueForeground1)'
                }}
              >
                {processStatus}
              </Text>
            </div>
          </div>
        )}
      </div>
    </Card>
  );
}
