// src/components/layout/Sidebar.tsx
import { useCallback } from "react";
import {
  DataBarVerticalRegular,
  GlobeRegular,
  PlugConnectedRegular,
  DocumentTextRegular,
  BookNumberRegular,
  DocumentEditRegular,
  WrenchRegular,
  SettingsRegular,
} from "@fluentui/react-icons";
import { useAppStore } from "../../stores/appStore";
import { useSettingsStore } from "../../stores/settingsStore";
import { useSingboxStore } from "../../stores/singboxStore";
import { StatusBadge } from "../ui/StatusBadge";
import type { AppPage } from "../../types/app";

const NAV_ITEMS = [
  { id: "overview" as AppPage, label: "Overview", icon: DataBarVerticalRegular },
  { id: "proxy" as AppPage, label: "Proxies", icon: GlobeRegular },
  { id: "connections" as AppPage, label: "Connections", icon: PlugConnectedRegular },
  { id: "logs" as AppPage, label: "Logs", icon: DocumentTextRegular },
  { id: "rules" as AppPage, label: "Rules", icon: BookNumberRegular },
  { id: "config" as AppPage, label: "Config", icon: DocumentEditRegular },
  { id: "custom" as AppPage, label: "Custom", icon: WrenchRegular },
] as const;

export function Sidebar() {
  const currentPage = useAppStore((s) => s.currentPage);
  const setCurrentPage = useAppStore((s) => s.setCurrentPage);
  const setSettingsPage = useSettingsStore((s) => s.setCurrentPage);
  const isRunning = useSingboxStore((s) => s.isRunning);

  const navigate = useCallback(
    async (page: AppPage) => {
      setCurrentPage(page);
      await setSettingsPage(page);
    },
    [setCurrentPage, setSettingsPage],
  );

  return (
    <aside
      className="flex flex-col bg-[var(--wb-surface-base)] border-r border-[var(--wb-border-subtle)] flex-shrink-0"
      style={{ width: "var(--wb-sidebar-width)" }}
    >
      <div className="px-4 py-4 border-b border-[var(--wb-border-subtle)]">
        <div className="text-base font-semibold text-[var(--wb-text-primary)]">
          Fresh Box
        </div>
        <div className="text-xs text-[var(--wb-text-secondary)] mt-0.5">
          sing-box client
        </div>
      </div>

      <nav className="flex-1 px-2 py-2 overflow-y-auto">
        {NAV_ITEMS.map((item) => {
          const Icon = item.icon;
          const active = currentPage === item.id;
          return (
            <button
              key={item.id}
              onClick={() => void navigate(item.id)}
              className={[
                "w-full flex items-center gap-3 px-3 py-2 text-sm rounded-[var(--wb-radius-md)] mb-0.5",
                "transition-colors duration-100 text-left relative",
                "focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[var(--wb-accent)]",
                active
                  ? "bg-[var(--wb-surface-selected)] text-[var(--wb-text-primary)]"
                  : "text-[var(--wb-text-secondary)] hover:bg-[var(--wb-surface-hover)] hover:text-[var(--wb-text-primary)]",
              ].join(" ")}
            >
              {active && (
                <span className="absolute left-0 top-1 bottom-1 w-0.5 bg-[var(--wb-accent)] rounded-full" />
              )}
              <Icon className="flex-shrink-0 text-base" />
              <span className="truncate">{item.label}</span>
            </button>
          );
        })}
      </nav>

      <div className="px-2 py-2 border-t border-[var(--wb-border-subtle)]">
        <div className="px-3 py-2 mb-1">
          <StatusBadge running={isRunning} />
        </div>
        <button
          onClick={() => void navigate("settings")}
          className={[
            "w-full flex items-center gap-3 px-3 py-2 text-sm rounded-[var(--wb-radius-md)]",
            "transition-colors duration-100 text-left relative",
            "focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[var(--wb-accent)]",
            currentPage === "settings"
              ? "bg-[var(--wb-surface-selected)] text-[var(--wb-text-primary)]"
              : "text-[var(--wb-text-secondary)] hover:bg-[var(--wb-surface-hover)] hover:text-[var(--wb-text-primary)]",
          ].join(" ")}
        >
          {currentPage === "settings" && (
            <span className="absolute left-0 top-1 bottom-1 w-0.5 bg-[var(--wb-accent)] rounded-full" />
          )}
          <SettingsRegular className="flex-shrink-0 text-base" />
          <span className="truncate">Settings</span>
        </button>
      </div>
    </aside>
  );
}

// src.vue/components/Sidebar.vue
<script setup lang="ts">
import { useAppStore } from "../stores/appStore";
import type { AppPage } from "../types/app";

const appStore = useAppStore();

function changePage(page: AppPage) {
  void appStore.setCurrentPage(page);
}
</script>

<template>
  <div class="sidebar">
    <div class="logo-container">
      <h1 class="logo">Fresh Box</h1>
      <p class="subtitle">sing-box Client</p>
    </div>
    <div class="nav-items">
      <button
        class="sidebar-item"
        :class="{ active: appStore.currentPage.value === 'overview' }"
        @click="changePage('overview')"
      >
        <span class="sidebar-icon">📊</span>
        Overview
      </button>
      <button
        class="sidebar-item"
        :class="{ active: appStore.currentPage.value === 'proxy' }"
        @click="changePage('proxy')"
      >
        <span class="sidebar-icon">🌐</span>
        Proxies
      </button>
      <button
        class="sidebar-item"
        :class="{ active: appStore.currentPage.value === 'connections' }"
        @click="changePage('connections')"
      >
        <span class="sidebar-icon">🔌</span>
        Connections
      </button>
      <button
        class="sidebar-item"
        :class="{ active: appStore.currentPage.value === 'logs' }"
        @click="changePage('logs')"
      >
        <span class="sidebar-icon">📜</span>
        Logs
      </button>
      <button
        class="sidebar-item"
        :class="{ active: appStore.currentPage.value === 'rules' }"
        @click="changePage('rules')"
      >
        <span class="sidebar-icon">📐</span>
        Rules
      </button>
      <button
        class="sidebar-item"
        :class="{ active: appStore.currentPage.value === 'config' }"
        @click="changePage('config')"
      >
        <span class="sidebar-icon">📝</span>
        Config
      </button>
      <button
        class="sidebar-item"
        :class="{ active: appStore.currentPage.value === 'custom' }"
        @click="changePage('custom')"
      >
        <span class="sidebar-icon">🎛️</span>
        Custom
      </button>
      <button
        class="sidebar-item"
        :class="{ active: appStore.currentPage.value === 'settings' }"
        @click="changePage('settings')"
      >
        <span class="sidebar-icon">⚙️</span>
        Settings
      </button>
    </div>
  </div>
</template>
